apiVersion: v1
kind: Service
metadata:
  name: mcp-zero-editor
  namespace: mcp-zero
  labels:
    app: mcp-zero-editor
spec:
  selector:
    app: mcp-zero-editor
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
